sudo: required

addons:
  chrome: stable

language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

branches:
  only:
    - dev

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  target-branch: master
  keep-history: false
  on:
    branch: dev
